language: php

php:
    # - 7.1 # will fail some tests at the moment
    # - 7.2 # will fail some tests at the moment
    - 7.3
    - 7.4

matrix:
    fast_finish: true

before_install:
    # install php-ext-snappy
    - git clone --recursive --depth=1 https://github.com/kjdev/php-ext-snappy.git
    - cd php-ext-snappy
    - export CXXFLAGS=-std=c++11
    - phpize
    - ./configure
    - make
    - make install
    - echo "extension = snappy.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    # disable XDebug for now
    - phpenv config-rm xdebug.ini

install:
    - cd $TRAVIS_BUILD_DIR
    - composer self-update
    - composer update

script:
    - cd $TRAVIS_BUILD_DIR
    - vendor/bin/phpunit tests
